name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * fri'
    # cron表达式,每周五16点执行一次，actions任务时区为UTC时区。 


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.TOKEN }}

    - name: Set git identity
      run : |
        git config --global user.email "xsp1343001800@qq.com"
        git config --global user.name "xsp1343001800"
    - name: Load upstream commits
      run: |
        git pull https://github.com/xsp1343001800/88-AutoSignMachine3040.git --log --no-commit --allow-unrelated-histories
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: main
        TZ: Asia/Shanghai
      run: git push origin $DOWNSTREAM_BRANCH --allow-unrelated-histories
      run: git push origin master --allow-unrelated-histories
